//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTapChi.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class TapChiBaiViet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TapChiBaiViet()
        {
            this.LichSuChinhSuas = new HashSet<LichSuChinhSua>();
            this.PhanBiens = new HashSet<PhanBien>();
            this.PhanCongs = new HashSet<PhanCong>();
            this.PhanCongBienTaps = new HashSet<PhanCongBienTap>();
            this.XuatBans = new HashSet<XuatBan>();
        }
    
        public int IDTapChiBaiViet { get; set; }
        public string TieuDe { get; set; }
        public string TacGia { get; set; }
        public string NoiDung { get; set; }
        public int IDLinhVuc { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public System.DateTime NgayGui { get; set; }
        public string TuKhoa { get; set; }
        public Nullable<int> IDNguoiGui { get; set; }
        public string DongTacGia { get; set; }
        public Nullable<int> TrangThaiPhanBien { get; set; }
        [AllowHtml]
        public string TomTat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuChinhSua> LichSuChinhSuas { get; set; }
        public virtual LinhVuc LinhVuc { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanBien> PhanBiens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanCong> PhanCongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanCongBienTap> PhanCongBienTaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XuatBan> XuatBans { get; set; }
    }
}
